In [1]:
import numpy as np
list=[1,2,3,4,5,6,7,8]
n=np.array(list)
print(n)

[1 2 3 4 5 6 7 8]


In [3]:
import numpy as np
arr= np.arange(30).reshape(6,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [7]:
import numpy as np
arr= np.zeros ((2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
import numpy as np
arr= np.ones((2,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
import numpy as np
arr= np.full((2,2),7)
print(arr)

[[7 7]
 [7 7]]


In [13]:
import numpy as np 
arr= np.arange(20).reshape(5,4)
print(arr[:,:])
print(arr[2:5,0:3])
print(arr[0:2,0:5])
print(arr[2:4,2:4])
print(arr[-3:-1,-3:-1])
print(arr[-4:-1,-4:-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 8  9 10]
 [12 13 14]
 [16 17 18]]
[[0 1 2 3]
 [4 5 6 7]]
[[10 11]
 [14 15]]
[[ 9 10]
 [13 14]]
[[ 4  5  6]
 [ 8  9 10]
 [12 13 14]]


In [19]:
import numpy as np
a= np.array(10)
b=np.array([1,1,1,1,1])
print(a.ndim)
print(b.ndim)

0
1
