In [3]:
#question 1 
import numpy as np
list = [1,2,3,4,5,6,7,8,9,10,11]
n = np.array(list)
print(n)


[ 1  2  3  4  5  6  7  8  9 10 11]


[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]


In [8]:
# question 2
import numpy as np
arr = np.arange(30).reshape(6,5)
print(arr)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [12]:
#question 4
import numpy as np

arr = np.full((2,4),7)
print(arr)


[[7 7 7 7]
 [7 7 7 7]]


In [14]:
#import numpy as np
#arr=np.zeros((2,4))
#print(arr)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [16]:
#Question 3
import numpy as np

arr = np.zeros((2,4))
print(arr)
arr = np.ones((2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
#question 5
import numpy as np
arr=np.arange(20).reshape(5,4)
print(arr[:,:])
print(arr[2:5, 0:3])
print(arr[0:2,0:5])
print(arr[2:4,2:4])
print(arr[-2:-2,3:-1])
print(arr[-4:-1,-4:-1])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 8  9 10]
 [12 13 14]
 [16 17 18]]
[[0 1 2 3]
 [4 5 6 7]]
[[10 11]
 [14 15]]
[]
[[ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
